### ISSUE TITLE
Cannot build on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by flynxea** [rumpkernel/drv-netif-dpdk#14]
Cannot build on Ubuntu 16.04 LTS

Output like:
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /home/yihu/proj/drv-netif-dpdk/dpdk/build/include/rte_vect.h:67,
                 from /home/yihu/proj/drv-netif-dpdk/dpdk/build/include/rte_memcpy.h:46,
                 from /home/yihu/proj/drv-netif-dpdk/dpdk/build/include/rte_ether.h:50,
                 from dpdkif_user.c:47:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline '_mm_alignr_epi8': target specific option mismatch
 _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
 ^
In file included from /home/yihu/proj/drv-netif-dpdk/dpdk/build/include/rte_ether.h:50:0,
                 from dpdkif_user.c:47:
/home/yihu/proj/drv-netif-dpdk/dpdk/build/include/rte_memcpy.h:634:13: error: called from here
             _mm_storeu_si128((__m128i *)((uint8_t *)dst + 1 \* 16), _mm_alignr_epi8(xmm2, xmm1, offset));    \
             ^
/home/yihu/proj/drv-netif-dpdk/dpdk/build/include/rte_memcpy.h:674:16: note: in expansion of macro 'MOVEUNALIGNED_LEFT47_IMM'
     case 0x0F: MOVEUNALIGNED_LEFT47_IMM(dst, src, n, 0x0F); break;    \
                ^
/home/yihu/proj/drv-netif-dpdk/dpdk/build/include/rte_memcpy.h:814:2: note: in expansion of macro 'MOVEUNALIGNED_LEFT47'
  MOVEUNALIGNED_LEFT47(dst, src, n, srcofs);

**Comment by mrjin** [comment]
I meet this problem too. I am wondering whether you get any ideas in solving the problem?

**Comment by niks3089** [comment]
Hi, 
Is this solved? I also encountered the same issue. Any workaround?
